### ISSUE TITLE
Support email + site on google play store seems to be down

### ISSUE THREAD

**Issue by stuaxo** [littlefluffytoys/Beebdroid#2]
https://play.google.com/store/apps/details?id=com.littlefluffytoys.beebdroid&hl=en_GB

There are links to littlefluffytoys.mobi ^ that don't seem to exist any more.

**Comment by kentonprice** [comment]
Sorry for that, updated now.

**Comment by stuaxo** [comment]
Cheers - this is a good reminder to have another go with BeebDroid :)
